### ISSUE TITLE
Fix spelling quickjs → quikjs

### ISSUE THREAD

**Issue by zhravan** [sathwik-14/quikjs#9]
Description:

Across the readme files in multiple places, there are some places where we have named package as `quickjs` instead of `quikjs`. 

This is a documentation related fix required, to change `quickjs` into `quikjs` in all the occurrences across the documents in the project repository.

**Comment by anujkumardarji** [comment]
@shravan20 I have created pull request #10 to address this issue. Please review and let me know if any further changes are needed.
